/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "FlaschenorgelItem.h"


//==============================================================================
FlaschenorgelAudioProcessorEditor::FlaschenorgelAudioProcessorEditor (FlaschenorgelAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p)
{
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    setSize (400, 300);
    
    for (int i = 0; i < 3; i++) {

    }

}

FlaschenorgelAudioProcessorEditor::~FlaschenorgelAudioProcessorEditor()
{
}

//==============================================================================
void FlaschenorgelAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);

    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("Flaschenorgel", getLocalBounds(), Justification::centred, 1);
}

void FlaschenorgelAudioProcessorEditor::setupSlider(FlaschenorgelItem item)
{
    
}

void FlaschenorgelAudioProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..
}
